<?php

declare(strict_types=1);

return [
    'perro' => [
        'name' => 'Perro',
        'emoji' => '🐶',
        'palette' => ['B' => '#2b211d', 'R' => '#b96f3a', 'K' => '#111111', 'P' => '#f58b83'],
        'matrix' => [
            '....BB......',
            '..BBRRBB....',
            '.BRRRRRRB...',
            'BRRKRRKRBB..',
            'BRRRRRRRRB..',
            'BRRRKKRRRB..',
            '.BRRPRRRB...',
            '..BRRRRB....',
            '..BBRRBB....',
            '..B.RR.B....',
            '.BB....BB...',
            '............',
        ],
    ],
    'gato' => [
        'name' => 'Gato',
        'emoji' => '🐱',
        'palette' => ['B' => '#282329', 'R' => '#9a72c7', 'K' => '#101010', 'P' => '#ff829f'],
        'matrix' => [
            'B........B..',
            'BB......BB..',
            'BRB....BRB..',
            'BRRBBBBRRB..',
            'BRRRRRRRRB..',
            'BRRKRRKRRB..',
            'BRRRKKRRRB..',
            'BRRRPPRRRB..',
            '.BRRRRRRB...',
            '..BRRRRB....',
            '..B.B.B.B...',
            '............',
        ],
    ],
    'zorro' => [
        'name' => 'Zorro',
        'emoji' => '🦊',
        'palette' => ['B' => '#2c211e', 'O' => '#ef7135', 'W' => '#fff4db', 'K' => '#111111'],
        'matrix' => [
            'BB......BB..',
            'BOB....BOB..',
            'BOOBBBOOB...',
            'BOOOOOOOB...',
            'BOOWWWOOB...',
            'BOWKOWKOB...',
            '.OWWWWWO....',
            '..WWKWW.....',
            '..BWWWOB....',
            '...BOOB.....',
            '....BB......',
            '............',
        ],
    ],
    'panda' => [
        'name' => 'Panda',
        'emoji' => '🐼',
        'palette' => ['B' => '#181818', 'W' => '#fffdf2', 'G' => '#8bd450'],
        'matrix' => [
            '.BB....BB...',
            'BBBB..BBBB..',
            'BWWBBBBWWB..',
            'BWWWWWWWWB..',
            'BWBWWWWBWB..',
            'BBBWBBWBBB..',
            'BWWBBBBWWB..',
            '.BWWWWWWB...',
            '..BBWWBB....',
            '..BGBBGB....',
            '...G..G.....',
            '............',
        ],
    ],
    'rana' => [
        'name' => 'Rana',
        'emoji' => '🐸',
        'palette' => ['B' => '#173b2b', 'G' => '#65c84b', 'L' => '#aee85d', 'W' => '#ffffff', 'P' => '#f36b91'],
        'matrix' => [
            '.BBB..BBB...',
            'BGGBBBGGB...',
            'BGWGBGWGB...',
            'BGGBBGGGB...',
            '.BGGGGGB....',
            'BGGLGGGGB...',
            'BGGGGGGGB...',
            'BGGBBBGGB...',
            '.BGPPGGB....',
            '..BGGGB.....',
            '.BB...BB....',
            '............',
        ],
    ],
    'unicornio' => [
        'name' => 'Unicornio',
        'emoji' => '🦄',
        'palette' => ['B' => '#36235a', 'W' => '#fff9ef', 'P' => '#ff76ad', 'Y' => '#ffd84a', 'C' => '#62dbe8'],
        'matrix' => [
            '.......Y....',
            '......YY....',
            '.B...YWB....',
            '.BB.BWWWB...',
            '.BPBWWWWB...',
            '..PWWBWWB...',
            '.PPWWWWWB...',
            '.PCWWWWB....',
            '..BWWWWB....',
            '...BWWWB....',
            '...B.B.B....',
            '............',
        ],
    ],
    'narval' => [
        'name' => 'Narval',
        'emoji' => '🐳',
        'palette' => ['B' => '#16324f', 'A' => '#5db8e8', 'L' => '#a9e4f7', 'W' => '#ffffff', 'Y' => '#f5c84b'],
        'matrix' => [
            '........Y...',
            '.......YY...',
            '......YY....',
            '.....B......',
            '..BBBBBBB...',
            '.BAAAAAAAB..',
            'BAALAAAAAAB.',
            'BAWALAAAAAB.',
            'BAAAAAAAAAB.',
            '.BLLLLLLLB..',
            '..BBB..BBB..',
            '............',
        ],
    ],
    'ballena' => [
        'name' => 'Ballena',
        'emoji' => '🐋',
        'palette' => ['B' => '#142c48', 'A' => '#397fbd', 'L' => '#8cc9e8', 'W' => '#ffffff'],
        'matrix' => [
            '.........A..',
            '......A.AA..',
            '.......A....',
            '............',
            '..BBBBBBB...',
            '.BAAAAAAABB.',
            'BAALAAAAAAB.',
            'BAWAAAAAAAB.',
            'BAAAAAAAAAB.',
            '.BLLLLLLLB..',
            '..BBBBBBB...',
            '............',
        ],
    ],
];
