<?php

declare(strict_types=1);

return [
    'perro' => [
        'name' => 'Perro',
        'emoji' => '🐶',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#5a3018',
            'D' => '#7a3f1d',
            'B' => '#b86734',
            'T' => '#d9955e',
            'H' => '#f3c58c',
            'W' => '#fff7e8',
            'R' => '#c83f4d',
            'S' => '#713c2c',
        ],
        'matrix' => [
            '................KKK....',
            '...............KTTTK...',
            '..............KTHHTK...',
            '.............KTHWHTK...',
            '............KTTTTTTK...',
            '...KK......KBTTRTTK....',
            '..KBTK....KBBTTTK......',
            '.KBBTK...KBBBBBK.......',
            'KBBBTTKKKBBBBBBK.......',
            '.KBBBBBBBBBBBBBK.......',
            '..KBBBBBBBBBBBK........',
            '...KBBBSSSBBBK.........',
            '....KSSSSSSK...........',
            '....KBBK.KBBK..........',
            '....KBBK.KBBK..........',
            '....KBTK.KBTK..........',
            '...KKBTK.KBTKK.........',
            '...KKKKK.KKKKK.........',
        ],
    ],
    'gato' => [
        'name' => 'Gato',
        'emoji' => '🐱',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#6b3218',
            'O' => '#e8862f',
            'D' => '#b85e1c',
            'L' => '#f2a34f',
            'G' => '#79a83b',
            'W' => '#fff8dc',
            'C' => '#f4d3a1',
            'P' => '#d96b72',
            'S' => '#98461f',
        ],
        'matrix' => [
            '.......................',
            '..............K...K....',
            '.............KOK.KOK...',
            '............KOOOKOOOK..',
            '...........KOOOOOOOOWK.',
            '..K........KOOOGKOGKCK.',
            '.KOKK.....KOOOOOOOCCPK.',
            'KOODOKKKKKOOOOOOODCCK..',
            'KOOODDOOOOOOOOOOOOCK...',
            '.KOOOOOOOOOOOOOOOCK....',
            '..KLOOOOODDOOOOOSK.....',
            '...KOOOOOOOOOOOSSK.....',
            '....KSSSSSSSSSSK.......',
            '.....KOSK..KOSK........',
            '.....KODK..KODK........',
            '.....KOCK..KOCK........',
            '....KKOCK.KKOCKK.......',
            '....KKKKK.KKKKKK.......',
        ],
    ],
    'zorro' => [
        'name' => 'Zorro',
        'emoji' => '🦊',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#7a2d16',
            'S' => '#c94420',
            'R' => '#e95724',
            'O' => '#f47a2a',
            'H' => '#ffaa45',
            'C' => '#e8c99b',
            'W' => '#fff3d6',
            'E' => '#110d0c',
        ],
        'matrix' => [
            '.......................',
            '................K......',
            '...............KRK.....',
            '....KK........KRRK.....',
            '..KKWWK......KRRRKK....',
            '.KWWCWWK...KKROOORRK...',
            'KWWCCWWRKKKROHOOORRK...',
            'KWWCORRRRRRROOOOWRRK...',
            '.KCORRRRRRRROOORKKK....',
            '..KORRRRRRRROORRK......',
            '...KRRRHHHHRRRRK.......',
            '....KRRROOORRRK........',
            '.....KRRRRRRRK.........',
            '.....KSSRRRSSK.........',
            '.....KSRK.KSRK.........',
            '.....KSRK.KSRK.........',
            '.....KSKK.KSKK.........',
            '.....KKK..KKK..........',
            '.......................',
        ],
    ],
    'panda' => [
        'name' => 'Panda',
        'emoji' => '🐼',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#303840',
            'B' => '#202a31',
            'W' => '#f4efe2',
            'G' => '#343a3f',
            'L' => '#ffffff',
            'P' => '#d88488',
            'E' => '#f4dca4',
            'N' => '#261719',
        ],
        'matrix' => [
            '.......................',
            '............KK.KK......',
            '...........KBBKBBK.....',
            '..........KBBBBBBBK....',
            '.........KBWWWWWBBBK...',
            '...KKK...KBWGWWGWBBK...',
            '..KBBBK.KBWWBGBWWBBK...',
            '.KBWWWKBWWWWWEWWWBBK...',
            'KBBWWWWWWWWWNWWWWWK....',
            'KBBWWWWWWWWWWWWWBK.....',
            '.KBBWWWWWWWWWWBBK......',
            '..KBBGGWWWWGGBBK.......',
            '...KBBBBGGGBBBK........',
            '....KBBBWWWBBK.........',
            '....KBBK.KBBK..........',
            '....KBWK.KBWK..........',
            '....KBBK.KBBK..........',
            '....KKK..KKK...........',
            '.......................',
        ],
    ],
    'rana' => [
        'name' => 'Rana',
        'emoji' => '🐸',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#2d5f3f',
            'D' => '#347a4a',
            'G' => '#58b947',
            'L' => '#9be564',
            'W' => '#fff8dc',
            'E' => '#17130f',
            'P' => '#ef6f78',
        ],
        'matrix' => [
            '.......................',
            '.....KKK.......KKK.....',
            '....KWWWK.....KWWWK....',
            '....KWEWK.....KWEWK....',
            '...KGGGGKKKKKKKGGGGK...',
            '..KGGGGGLLLLLGGGGGGGK..',
            '.KGGGGGLLLLLLLGGGGGGK..',
            '.KGGGGLLDGGGLLDGGGGGK..',
            '..KGGGGGGPPGGGGGGGGK...',
            '...KGGGGGGGGGGGGGGK....',
            '..KKKGGGGGGGGGGGKKK....',
            '.KDDGKGGGGGGGGGKDGDK...',
            'KDDGGKGGGGGGGGGKGGDDK..',
            '.KGGGKGGGLLLGGGKGGGK...',
            '..KKK.KGGLLLGGK.KKK....',
            '...KGGK.KDDDK.KGGK.....',
            '..KDDDK..KKK..KDDDK....',
            '..KKK.........KKK......',
        ],
    ],
    'unicornio' => [
        'name' => 'Unicornio',
        'emoji' => '🦄',
        'pixelSize' => 9,
        'palette' => [
            '1' => '#0c8fe7',
            '2' => '#1497e5',
            '3' => '#fef8ac',
            '4' => '#f47027',
            '5' => '#fd383d',
            '6' => '#62bf48',
            '7' => '#1397e5',
            '8' => '#711d7a',
            '9' => '#0d0c09',
            'A' => '#89c3f1',
            'B' => '#f1dc3f',
        ],
        'matrix' => [
            '......................1',
            '.................555.1.',
            '................54441..',
            '...............113334..',
            '..............311111...',
            '.....11A......6119111..',
            '......1A......7611111..',
            '.......1A.....8711.....',
            '...821.1A......871.....',
            '..826.1BBBB11111811....',
            '.8263.1BBBB11111111....',
            '.2635.1BBBB11111111....',
            '2634..1BBBB11111111....',
            '6......111.....111.....',
            '.......11.......11.....',
            '.......11.......11.....',
            '.......11.......11.....',
            '.......11.......11.....',
        ],
    ],
    'narval' => [
        'name' => 'Narval',
        'emoji' => '🐳',
        'pixelSize' => 9,
        'palette' => [
            '1' => '#0c8fe7',
            '2' => '#d29027',
            '3' => '#000000',
            '4' => '#b1e7ff',
            '5' => '#90c8eb',
            '6' => '#82c3eb',
            '7' => '#6eb5e5',
            '8' => '#b6f0ff',
            '9' => '#86c4eb',
            'A' => '#e91e63',
            'B' => '#d59327',
            'C' => '#009ede',
            'D' => '#3ac6f1',
            'E' => '#6dcff3',
            'F' => '#009fdf',
            'G' => '#3bc7f1',
        ],
        'matrix' => [
            '2......................',
            '.2.....................',
            '..2....................',
            '...B..441111116........',
            '....441111111116.......',
            '...84111111111116...1.1',
            '...411311111111116...1.',
            '...1AA111111111115555..',
            '...11111777999999999...',
            '.......................',
            '.....CC.CDDDC.CCC......',
            '....E..CCCDCCCC...E....',
            '...C.....CFFG..........',
            '.....G....CC.....C.....',
            '..........CC...........',
            '..........CC...........',
        ],
    ],
    'ballena' => [
        'name' => 'Ballena',
        'emoji' => '🐋',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#1d4563',
            'D' => '#27658b',
            'B' => '#397fbd',
            'M' => '#3f91b6',
            'C' => '#a8edf2',
            'L' => '#74c8dd',
            'V' => '#c8e8df',
            'W' => '#fff8dc',
            'S' => '#9de5ef',
        ],
        'matrix' => [
            '..................S.S..',
            '.................S.S...',
            '..................S....',
            '.................SSS...',
            '..................S....',
            '.......KKKKKKKKKK......',
            '.....KKBBBBBBBBBBBK....',
            '...KKBMCCMMMMMMMMMMKK..',
            '..KBBMMMMMLLLLMMMMMWBK.',
            '.KBBBMMMMMMMMMMMMMMMMK.',
            'KDDDBMMMMMMMMMMMMMMMDK.',
            '.KDDKBBMMMMMMMMMMMMMMK.',
            '..KK.KBBVVVVVVVVVVMMK..',
            '......KBBVVVVVVVVMKK...',
            '.......KKBBVVVKKK......',
            '.........KBDDKK........',
            '..........KKK..........',
            '.......................',
        ],
    ],
    'elefante' => [
        'name' => 'Elefante Phpeitor',
        'emoji' => '🐘',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#6d787d',
            'G' => '#a9def4',
            'L' => '#d6f3ff',
            'D' => '#8f9da3',
            'W' => '#111111',
        ],
        'matrix' => [
            '.......................',
            '........KKKKKKKK.......',
            '......KKGGGGGGGGKK.....',
            '.....KGGGGGGGGGGGGK....',
            '....KGGGGGGGGGGGGGGK...',
            '...KGGGGGGGGGGGGGGGGK..',
            '..KGGGGGGGGGGGGGGGGGK..',
            '.KGGGLLLGGGGGGGGGWGGK..',
            '.KGGLLLLLGGGGGGGGGGGK..',
            'KGGLLLLLLGGGGGGGGGGK...',
            'KGGLLLLLLGGGGGGGGGGK...',
            'KGGGLLLLGGGGGGGGGGK....',
            'KGGGGGGGGGGGGGGGDK.....',
            'KGGGGGGGGGGGGGGDK......',
            '.KGGGGGGGGGGGGDK.......',
            '..KGGGGDDGGGGK.KK......',
            '..KGGGDK.KGGGK.KGK.....',
            '..KGGGDK.KGGGK.KGK.....',
            '..KGGGDK.KGGGK.KGK.....',
            '..KGGGDK.KGGGK.KDK.....',
            '..KDDDK..KDDDK.KK......',
            '..KKKK...KKKK..........',
            '.......................',
        ],
    ],
    'tigre' => [
        'name' => 'Tigre',
        'emoji' => '🐯',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#231812',
            'O' => '#f47a2a',
            'H' => '#ffaa45',
            'S' => '#7a2d16',
            'W' => '#fff4d6',
            'N' => '#111111',
            'D' => '#b84a1b',
        ],
        'matrix' => [
            '.......................',
            '..............K...K....',
            '.............KOK.KOK...',
            '............KOOOKOOOK..',
            '...........KOSOOSOOWK..',
            '..HH......KOOOOOOOOONK.',
            '.HOOHK...KOSOOSOOOOK...',
            'HOOOHKKKKOOOOOOOOOOK...',
            '.HOOOOOOOOOOOOOOOOSK...',
            '..HOOOOOOOOOOOOOOOK....',
            '...KOOOOOOOOOOOOOK.....',
            '....KSOOSOOSOOSK.......',
            '.....DOOOOOOOOD........',
            '.....KDDDDDDDK.........',
            '.....KODK.KODK.........',
            '.....KODK.KODK.........',
            '.....KOKK.KOKK.........',
            '.....KKK..KKK..........',
        ],
    ],
];
