<?php

declare(strict_types=1);

return [
    'perro' => [
        'name' => 'Perro',
        'emoji' => '🐶',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#241915',
            'D' => '#563126',
            'B' => '#9a5838',
            'T' => '#d9955e',
            'H' => '#f3c58c',
            'W' => '#fff7e8',
            'R' => '#c83f4d',
            'S' => '#713c2c',
        ],
        'matrix' => [
            '................KKK....',
            '...............KDDDK...',
            '..............KDDBBK...',
            '..............KBBBTTKK.',
            '...KK........KBBHTTTTKK',
            '..KTBK.....KBBBTTWKTKK.',
            '.KBTBK.....KBBBBTTTTKKK',
            'KBBTBKKKKKBBBBBBTTKKKK.',
            '.KBBBBBBTTBBBBBRRBK....',
            '..KBTBBBBBBBBBRRBTK....',
            '...KBBBBBBBBBBBBBK.....',
            '....KKSSSSSSSSSKK......',
            '.....KSSK....KSSK......',
            '.....KBBK....KBBK......',
            '.....KBBK....KBBK......',
            '.....KBTK....KBTK......',
            '....KKBTK...KKBTKK.....',
            '....KKKKK...KKKKKK.....',
        ],
    ],
    'gato' => [
        'name' => 'Gato',
        'emoji' => '🐱',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#211915',
            'O' => '#c96b28',
            'D' => '#7d361d',
            'L' => '#f2a34f',
            'G' => '#79a83b',
            'W' => '#fff8dc',
            'C' => '#f4d3a1',
            'P' => '#d96b72',
            'S' => '#98461f',
        ],
        'matrix' => [
            '.KK..............K.K...',
            'KDDK.............KOKK..',
            'KOODK...........KOOOKK.',
            'KOOODK..........KOOOOOK',
            '.KOOOK.........KOLGGWKK',
            '..KODK........KOOOGKCKK',
            '...KOK.......KDDOOCCPKK',
            '...KOKKKKKKKKOOOOODCCKK',
            '...KOOOOOOOOOOOOOOCK...',
            '....KLOOOOOODDOOOOCK...',
            '....KOOOOOOOOOOOSSK....',
            '.....KSSSSSSSSSSSK.....',
            '......KSSK...KSSK......',
            '......KOOK...KOOK......',
            '......KODK...KODK......',
            '......KOCK...KOCK......',
            '.....KKOCK..KKOCKK.....',
            '.....KKKKK..KKKKKK.....',
        ],
    ],
    'zorro' => [
        'name' => 'Zorro',
        'emoji' => '🦊',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#2a1715',
            'S' => '#9f2f1f',
            'R' => '#e95724',
            'O' => '#f47a2a',
            'H' => '#ffaa45',
            'C' => '#e8c99b',
            'W' => '#fff3d6',
            'E' => '#110d0c',
        ],
        'matrix' => [
            '.......................',
            '..............K...K....',
            '..KK.........KRK.KRK...',
            '.KWWKK......KRRRKRRRK..',
            'KWWWWWKK...KROOOORRRRK.',
            'KWWCCWWRK.KROHOORKRRRK.',
            'KWWCORRRKKKROOOORRKKKEK',
            '.KCORRRRRRRROOOORRKRKK.',
            '..KORRRRRRRROOOORRRRK..',
            '...KRRRHHHHRRRRRRRRK...',
            '....KRRROOORRRRRRRK....',
            '.....KRRRRRRRRRRRK.....',
            '......KSSRRRRRSSSK.....',
            '......KSRK....KSRK.....',
            '......KSRK....KSRK.....',
            '......KSKK....KSKK.....',
            '......KKK.....KKK......',
            '.......................',
        ],
    ],
    'panda' => [
        'name' => 'Panda',
        'emoji' => '🐼',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#0d1012',
            'B' => '#17191c',
            'W' => '#f4efe2',
            'G' => '#343a3f',
            'L' => '#ffffff',
            'P' => '#d88488',
            'E' => '#f4dca4',
            'N' => '#261719',
        ],
        'matrix' => [
            '.......................',
            '..............KK.KK....',
            '.............KPPKPPK...',
            '............KBBBBBBBK..',
            '...KGGGGK...KBWWWWBBBK.',
            '.KBKWWWWWKKKBWWGWWGBBBK',
            'KBBWWWWWWWBBBWBGKWGBBBK',
            'KBBWLLWWWWBBWWEWWKWWBBK',
            '.KBBWWWWWWWBWWWNWWWWBBK',
            '..KBBWWWWWWWWWWWWWBBBK.',
            '...KBBGGWWWWWWWWGBBBK..',
            '....KBBBBGGGGGBBBBBK...',
            '.....KBBBWWWWBBBBBK....',
            '.....KBBBK..KBBBK......',
            '.....KBWBK..KBWBK......',
            '.....KBBBK..KBBBK......',
            '.....KKKK...KKKK.......',
            '.......................',
        ],
    ],
    'rana' => [
        'name' => 'Rana',
        'emoji' => '🐸',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#10251f',
            'D' => '#28523a',
            'G' => '#58b947',
            'L' => '#9be564',
            'W' => '#fff8dc',
            'E' => '#17130f',
            'P' => '#ef6f78',
        ],
        'matrix' => [
            '.......................',
            '....KKKK.......KKK.....',
            '...KWWWWK......KWWWK...',
            '...KWEWWKKKKKKKWEWK....',
            '..KGGGGGLLLLLGGGGGGK...',
            '.KGGGGGLLLLLLGGGGGGGK..',
            '.KGGGGLLLLLLLLGGGGGGK..',
            '..KGGGLLDGGGGDLLGGGK...',
            '...KGGGGGGPPGGGGGGK....',
            '....KKGGGGGGGGGGKK.....',
            '.KKKK.KGGGGGGGGGK.KKKK.',
            'KDDDGKKGGGGGGGGGKKGDDDK',
            'KDDGGGKGGGGGGGGGGKGGDDK',
            '.KGGGGKGGGLLLGGGKGGGGK.',
            '..KKKK.KGGLLLGGK.KKKK..',
            '.KGGGK..KGDDDGK..KGGGK.',
            'KKDDDK...KK.KK...KDDDKK',
            '.KKKK.............KKKK.',
        ],
    ],
    'unicornio' => [
        'name' => 'Unicornio',
        'emoji' => '🦄',
        'pixelSize' => 9,
        'palette' => [
            '1' => '#0c8fe7',
            '2' => '#1497e5',
            '3' => '#fef8ac',
            '4' => '#f47027',
            '5' => '#fd383d',
            '6' => '#62bf48',
            '7' => '#1397e5',
            '8' => '#711d7a',
            '9' => '#0d0c09',
            'A' => '#89c3f1',
            'B' => '#f1dc3f',
        ],
        'matrix' => [
            '......................1',
            '.................555.1.',
            '................54441..',
            '...............113334..',
            '..............311111...',
            '.....11A......6119111..',
            '......1A......7611111..',
            '.......1A.....8711.....',
            '...821.1A......871.....',
            '..826.1BBBB11111811....',
            '.8263.1BBBB11111111....',
            '.2635.1BBBB11111111....',
            '2634..1BBBB11111111....',
            '6......111.....111.....',
            '.......11.......11.....',
            '.......11.......11.....',
            '.......11.......11.....',
            '.......11.......11.....',
        ],
    ],
    'narval' => [
        'name' => 'Narval',
        'emoji' => '🐳',
        'pixelSize' => 9,
        'palette' => [
            '1' => '#0c8fe7',
            '2' => '#d29027',
            '3' => '#000000',
            '4' => '#b1e7ff',
            '5' => '#90c8eb',
            '6' => '#82c3eb',
            '7' => '#6eb5e5',
            '8' => '#b6f0ff',
            '9' => '#86c4eb',
            'A' => '#e91e63',
            'B' => '#d59327',
            'C' => '#009ede',
            'D' => '#3ac6f1',
            'E' => '#6dcff3',
            'F' => '#009fdf',
            'G' => '#3bc7f1',
        ],
        'matrix' => [
            '2......................',
            '.2.....................',
            '..2....................',
            '...B..441111116........',
            '....441111111116.......',
            '...84111111111116...1.1',
            '...411311111111116...1.',
            '...1AA111111111115555..',
            '...11111777999999999...',
            '.......................',
            '.....CC.CDDDC.CCC......',
            '....E..CCCDCCCC...E....',
            '...C.....CFFG..........',
            '.....G....CC.....C.....',
            '..........CC...........',
            '..........CC...........',
        ],
    ],
    'ballena' => [
        'name' => 'Ballena',
        'emoji' => '🐋',
        'pixelSize' => 9,
        'palette' => [
            'K' => '#10283d',
            'D' => '#1d4563',
            'B' => '#27658b',
            'M' => '#3f91b6',
            'C' => '#a8edf2',
            'L' => '#74c8dd',
            'V' => '#c8e8df',
            'W' => '#fff8dc',
            'S' => '#9de5ef',
        ],
        'matrix' => [
            '..................S.S..',
            '.................S.S...',
            '..................S....',
            '.................SSS...',
            '..................S....',
            '...KK....KKKKKKKKK.....',
            '..KBBK.KKBBBBBBBBBBKK..',
            '.KBBBKKBMCCMMMMMMMMMMKK',
            '..KBBBBMMMMMLLLLMMMWKBK',
            '....KBBMMMMMMMMMMMMMMMK',
            '..KBBBBMMMMMMMMMMMMMMDK',
            '.KDDDKKBMMMMMMMMMMMMMMK',
            '..KDDK.KBBVVVVVVVVVVMMK',
            '...KK..KBBVVVVVVVVVMKK.',
            '.........KKBBVVVKKK....',
            '..........KBDDKK.......',
            '...........KKK.........',
            '.......................',
        ],
    ],
];
